// @generated by protobuf-ts 2.11.1 with parameter long_type_number
// @generated from protobuf file "apis/protobuf/main/corev1/corev1.proto" (package "octelium.api.main.core.v1", syntax proto3)
// tslint:disable
//
// Copyright Octelium Labs, LLC. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MainService } from "./corev1.js";
import type { ConfigList } from "./corev1.js";
import type { ListConfigOptions } from "./corev1.js";
import type { Config } from "./corev1.js";
import type { Authenticator } from "./corev1.js";
import type { AuthenticatorList } from "./corev1.js";
import type { ListAuthenticatorOptions } from "./corev1.js";
import type { ClusterConfig } from "./corev1.js";
import type { GetClusterConfigRequest } from "./corev1.js";
import type { Gateway } from "./corev1.js";
import type { GatewayList } from "./corev1.js";
import type { ListGatewayOptions } from "./corev1.js";
import type { RegionList } from "./corev1.js";
import type { ListRegionOptions } from "./corev1.js";
import type { Region } from "./corev1.js";
import type { IdentityProviderList } from "./corev1.js";
import type { ListIdentityProviderOptions } from "./corev1.js";
import type { IdentityProvider } from "./corev1.js";
import type { CredentialToken } from "./corev1.js";
import type { GenerateCredentialTokenRequest } from "./corev1.js";
import type { CredentialList } from "./corev1.js";
import type { ListCredentialOptions } from "./corev1.js";
import type { Credential } from "./corev1.js";
import type { Device } from "./corev1.js";
import type { DeviceList } from "./corev1.js";
import type { ListDeviceOptions } from "./corev1.js";
import type { GroupList } from "./corev1.js";
import type { ListGroupOptions } from "./corev1.js";
import type { Group } from "./corev1.js";
import type { SecretList } from "./corev1.js";
import type { ListSecretOptions } from "./corev1.js";
import type { Secret } from "./corev1.js";
import type { Session } from "./corev1.js";
import type { SessionList } from "./corev1.js";
import type { ListSessionOptions } from "./corev1.js";
import type { ServiceList } from "./corev1.js";
import type { ListServiceOptions } from "./corev1.js";
import type { Service } from "./corev1.js";
import type { NamespaceList } from "./corev1.js";
import type { ListNamespaceOptions } from "./corev1.js";
import type { Namespace } from "./corev1.js";
import type { UserList } from "./corev1.js";
import type { ListUserOptions } from "./corev1.js";
import type { User } from "./corev1.js";
import type { GetOptions } from "../metav1/metav1.js";
import type { OperationResult } from "../metav1/metav1.js";
import type { DeleteOptions } from "../metav1/metav1.js";
import type { PolicyList } from "./corev1.js";
import type { ListPolicyOptions } from "./corev1.js";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Policy } from "./corev1.js";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service octelium.api.main.core.v1.MainService
 */
export interface IMainServiceClient {
    /**
     * CreatePolicy creates a Policy
     *
     * @generated from protobuf rpc: CreatePolicy
     */
    createPolicy(input: Policy, options?: RpcOptions): UnaryCall<Policy, Policy>;
    /**
     * ListPolicy lists Policy
     *
     * @generated from protobuf rpc: ListPolicy
     */
    listPolicy(input: ListPolicyOptions, options?: RpcOptions): UnaryCall<ListPolicyOptions, PolicyList>;
    /**
     * UpdatePolicy updates a Policy
     *
     * @generated from protobuf rpc: UpdatePolicy
     */
    updatePolicy(input: Policy, options?: RpcOptions): UnaryCall<Policy, Policy>;
    /**
     * DeletePolicy deletes a Policy
     *
     * @generated from protobuf rpc: DeletePolicy
     */
    deletePolicy(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * GetPolicy retrieves a specific Policy
     *
     * @generated from protobuf rpc: GetPolicy
     */
    getPolicy(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Policy>;
    /**
     * CreateUser creates a User
     *
     * @generated from protobuf rpc: CreateUser
     */
    createUser(input: User, options?: RpcOptions): UnaryCall<User, User>;
    /**
     * ListUser lists Users
     *
     * @generated from protobuf rpc: ListUser
     */
    listUser(input: ListUserOptions, options?: RpcOptions): UnaryCall<ListUserOptions, UserList>;
    /**
     * UpdateUser updates a User
     *
     * @generated from protobuf rpc: UpdateUser
     */
    updateUser(input: User, options?: RpcOptions): UnaryCall<User, User>;
    /**
     * DeleteUser deletes a User
     *
     * @generated from protobuf rpc: DeleteUser
     */
    deleteUser(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * GetUser retrieves a specific User
     *
     * @generated from protobuf rpc: GetUser
     */
    getUser(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, User>;
    /**
     * CreateNamespace creates a Namespace
     *
     * @generated from protobuf rpc: CreateNamespace
     */
    createNamespace(input: Namespace, options?: RpcOptions): UnaryCall<Namespace, Namespace>;
    /**
     * UpdateNamespace updates a Namespace
     *
     * @generated from protobuf rpc: UpdateNamespace
     */
    updateNamespace(input: Namespace, options?: RpcOptions): UnaryCall<Namespace, Namespace>;
    /**
     * ListNamespace lists Namespaces
     *
     * @generated from protobuf rpc: ListNamespace
     */
    listNamespace(input: ListNamespaceOptions, options?: RpcOptions): UnaryCall<ListNamespaceOptions, NamespaceList>;
    /**
     * DeleteNamespace deletes a Namespace
     *
     * @generated from protobuf rpc: DeleteNamespace
     */
    deleteNamespace(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * GetNamespace retrieves a specific Namespace
     *
     * @generated from protobuf rpc: GetNamespace
     */
    getNamespace(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Namespace>;
    /**
     * CreateService creates a Service
     *
     * @generated from protobuf rpc: CreateService
     */
    createService(input: Service, options?: RpcOptions): UnaryCall<Service, Service>;
    /**
     * ListService lists Services
     *
     * @generated from protobuf rpc: ListService
     */
    listService(input: ListServiceOptions, options?: RpcOptions): UnaryCall<ListServiceOptions, ServiceList>;
    /**
     * UpdateService updates a Service
     *
     * @generated from protobuf rpc: UpdateService
     */
    updateService(input: Service, options?: RpcOptions): UnaryCall<Service, Service>;
    /**
     * DeleteService deletes a Service
     *
     * @generated from protobuf rpc: DeleteService
     */
    deleteService(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * GetService retrieves a specific Service
     *
     * @generated from protobuf rpc: GetService
     */
    getService(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Service>;
    /**
     * ListSession lists Sessions
     *
     * @generated from protobuf rpc: ListSession
     */
    listSession(input: ListSessionOptions, options?: RpcOptions): UnaryCall<ListSessionOptions, SessionList>;
    /**
     * DeleteSession deletes a Session
     *
     * @generated from protobuf rpc: DeleteSession
     */
    deleteSession(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * GetSession retrieves a specific Session
     *
     * @generated from protobuf rpc: GetSession
     */
    getSession(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Session>;
    /**
     * UpdateSession updates a Session
     *
     * @generated from protobuf rpc: UpdateSession
     */
    updateSession(input: Session, options?: RpcOptions): UnaryCall<Session, Session>;
    /**
     * CreateSecret creates a Secret
     *
     * @generated from protobuf rpc: CreateSecret
     */
    createSecret(input: Secret, options?: RpcOptions): UnaryCall<Secret, Secret>;
    /**
     * ListSecret lists Secrets
     *
     * @generated from protobuf rpc: ListSecret
     */
    listSecret(input: ListSecretOptions, options?: RpcOptions): UnaryCall<ListSecretOptions, SecretList>;
    /**
     * DeleteSecret deletes a Secret
     *
     * @generated from protobuf rpc: DeleteSecret
     */
    deleteSecret(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * GetSecret retrieves a specific Secret
     *
     * @generated from protobuf rpc: GetSecret
     */
    getSecret(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Secret>;
    /**
     * UpdateSecret creates a Secret
     *
     * @generated from protobuf rpc: UpdateSecret
     */
    updateSecret(input: Secret, options?: RpcOptions): UnaryCall<Secret, Secret>;
    /**
     * CreateGroup creates a Group
     *
     * @generated from protobuf rpc: CreateGroup
     */
    createGroup(input: Group, options?: RpcOptions): UnaryCall<Group, Group>;
    /**
     * ListGroup lists Groups
     *
     * @generated from protobuf rpc: ListGroup
     */
    listGroup(input: ListGroupOptions, options?: RpcOptions): UnaryCall<ListGroupOptions, GroupList>;
    /**
     * UpdateGroup updates a Group
     *
     * @generated from protobuf rpc: UpdateGroup
     */
    updateGroup(input: Group, options?: RpcOptions): UnaryCall<Group, Group>;
    /**
     * DeleteGroup deletes a Group
     *
     * @generated from protobuf rpc: DeleteGroup
     */
    deleteGroup(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * GetGroup retrieves a specific Group
     *
     * @generated from protobuf rpc: GetGroup
     */
    getGroup(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Group>;
    /**
     * ListDevice lists Devices
     *
     * @generated from protobuf rpc: ListDevice
     */
    listDevice(input: ListDeviceOptions, options?: RpcOptions): UnaryCall<ListDeviceOptions, DeviceList>;
    /**
     * DeleteDevice deletes a Device
     *
     * @generated from protobuf rpc: DeleteDevice
     */
    deleteDevice(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * GetDevice retrieves a specific Device
     *
     * @generated from protobuf rpc: GetDevice
     */
    getDevice(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Device>;
    /**
     * UpdateDevice updates a Device
     *
     * @generated from protobuf rpc: UpdateDevice
     */
    updateDevice(input: Device, options?: RpcOptions): UnaryCall<Device, Device>;
    /**
     * CreateCredential creates a Credential
     *
     * @generated from protobuf rpc: CreateCredential
     */
    createCredential(input: Credential, options?: RpcOptions): UnaryCall<Credential, Credential>;
    /**
     * UpdateCredential creates a Credential
     *
     * @generated from protobuf rpc: UpdateCredential
     */
    updateCredential(input: Credential, options?: RpcOptions): UnaryCall<Credential, Credential>;
    /**
     * DeleteCredential deletes a Credential
     *
     * @generated from protobuf rpc: DeleteCredential
     */
    deleteCredential(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * ListCredential lists Credentials
     *
     * @generated from protobuf rpc: ListCredential
     */
    listCredential(input: ListCredentialOptions, options?: RpcOptions): UnaryCall<ListCredentialOptions, CredentialList>;
    /**
     * GetCredential retrieves a specific Credential
     *
     * @generated from protobuf rpc: GetCredential
     */
    getCredential(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Credential>;
    /**
     * GenerateCredentialToken generates/rotates a Credential token
     *
     * @generated from protobuf rpc: GenerateCredentialToken
     */
    generateCredentialToken(input: GenerateCredentialTokenRequest, options?: RpcOptions): UnaryCall<GenerateCredentialTokenRequest, CredentialToken>;
    /**
     * CreateIdentityProvider creates an IdentityProvider
     *
     * @generated from protobuf rpc: CreateIdentityProvider
     */
    createIdentityProvider(input: IdentityProvider, options?: RpcOptions): UnaryCall<IdentityProvider, IdentityProvider>;
    /**
     * GetIdentityProvider retrieves a specific IdentityProvider
     *
     * @generated from protobuf rpc: GetIdentityProvider
     */
    getIdentityProvider(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, IdentityProvider>;
    /**
     * ListIdentityProvider lists IdentityProviders
     *
     * @generated from protobuf rpc: ListIdentityProvider
     */
    listIdentityProvider(input: ListIdentityProviderOptions, options?: RpcOptions): UnaryCall<ListIdentityProviderOptions, IdentityProviderList>;
    /**
     * UpdateIdentityProvider updates an UpdateIdentityProvider
     *
     * @generated from protobuf rpc: UpdateIdentityProvider
     */
    updateIdentityProvider(input: IdentityProvider, options?: RpcOptions): UnaryCall<IdentityProvider, IdentityProvider>;
    /**
     * DeleteIdentityProvider deletes an IdentityProvider
     *
     * @generated from protobuf rpc: DeleteIdentityProvider
     */
    deleteIdentityProvider(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * GetRegion retrieves a specific Region
     *
     * @generated from protobuf rpc: GetRegion
     */
    getRegion(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Region>;
    /**
     * ListRegion lists Regions
     *
     * @generated from protobuf rpc: ListRegion
     */
    listRegion(input: ListRegionOptions, options?: RpcOptions): UnaryCall<ListRegionOptions, RegionList>;
    /**
     * ListGateway lists Gateways
     *
     * @generated from protobuf rpc: ListGateway
     */
    listGateway(input: ListGatewayOptions, options?: RpcOptions): UnaryCall<ListGatewayOptions, GatewayList>;
    /**
     * GetGateway retrieves a specific Gateway
     *
     * @generated from protobuf rpc: GetGateway
     */
    getGateway(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Gateway>;
    /**
     * GetClusterConfig gets the Cluster Configuration.
     *
     * @generated from protobuf rpc: GetClusterConfig
     */
    getClusterConfig(input: GetClusterConfigRequest, options?: RpcOptions): UnaryCall<GetClusterConfigRequest, ClusterConfig>;
    /**
     * UpdateConfig updates the Cluster Configuration.
     *
     * @generated from protobuf rpc: UpdateClusterConfig
     */
    updateClusterConfig(input: ClusterConfig, options?: RpcOptions): UnaryCall<ClusterConfig, ClusterConfig>;
    /**
     * ListAuthenticator lists Authenticators
     *
     * @generated from protobuf rpc: ListAuthenticator
     */
    listAuthenticator(input: ListAuthenticatorOptions, options?: RpcOptions): UnaryCall<ListAuthenticatorOptions, AuthenticatorList>;
    /**
     * DeleteAuthenticator deletes an Authenticator
     *
     * @generated from protobuf rpc: DeleteAuthenticator
     */
    deleteAuthenticator(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * GetAuthenticator retrieves a specific Authenticator
     *
     * @generated from protobuf rpc: GetAuthenticator
     */
    getAuthenticator(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Authenticator>;
    /**
     * UpdateAuthenticator updates an Authenticator
     *
     * @generated from protobuf rpc: UpdateAuthenticator
     */
    updateAuthenticator(input: Authenticator, options?: RpcOptions): UnaryCall<Authenticator, Authenticator>;
    /**
     * CreateConfig creates a Config
     *
     * @generated from protobuf rpc: CreateConfig
     */
    createConfig(input: Config, options?: RpcOptions): UnaryCall<Config, Config>;
    /**
     * ListConfig lists Configs
     *
     * @generated from protobuf rpc: ListConfig
     */
    listConfig(input: ListConfigOptions, options?: RpcOptions): UnaryCall<ListConfigOptions, ConfigList>;
    /**
     * UpdateConfig updates a Config
     *
     * @generated from protobuf rpc: UpdateConfig
     */
    updateConfig(input: Config, options?: RpcOptions): UnaryCall<Config, Config>;
    /**
     * DeleteConfig deletes a Config
     *
     * @generated from protobuf rpc: DeleteConfig
     */
    deleteConfig(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * GetConfig retrieves a specific Config
     *
     * @generated from protobuf rpc: GetConfig
     */
    getConfig(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Config>;
}
/**
 * @generated from protobuf service octelium.api.main.core.v1.MainService
 */
export class MainServiceClient implements IMainServiceClient, ServiceInfo {
    typeName = MainService.typeName;
    methods = MainService.methods;
    options = MainService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * CreatePolicy creates a Policy
     *
     * @generated from protobuf rpc: CreatePolicy
     */
    createPolicy(input: Policy, options?: RpcOptions): UnaryCall<Policy, Policy> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Policy, Policy>("unary", this._transport, method, opt, input);
    }
    /**
     * ListPolicy lists Policy
     *
     * @generated from protobuf rpc: ListPolicy
     */
    listPolicy(input: ListPolicyOptions, options?: RpcOptions): UnaryCall<ListPolicyOptions, PolicyList> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListPolicyOptions, PolicyList>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdatePolicy updates a Policy
     *
     * @generated from protobuf rpc: UpdatePolicy
     */
    updatePolicy(input: Policy, options?: RpcOptions): UnaryCall<Policy, Policy> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<Policy, Policy>("unary", this._transport, method, opt, input);
    }
    /**
     * DeletePolicy deletes a Policy
     *
     * @generated from protobuf rpc: DeletePolicy
     */
    deletePolicy(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * GetPolicy retrieves a specific Policy
     *
     * @generated from protobuf rpc: GetPolicy
     */
    getPolicy(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Policy> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Policy>("unary", this._transport, method, opt, input);
    }
    /**
     * CreateUser creates a User
     *
     * @generated from protobuf rpc: CreateUser
     */
    createUser(input: User, options?: RpcOptions): UnaryCall<User, User> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<User, User>("unary", this._transport, method, opt, input);
    }
    /**
     * ListUser lists Users
     *
     * @generated from protobuf rpc: ListUser
     */
    listUser(input: ListUserOptions, options?: RpcOptions): UnaryCall<ListUserOptions, UserList> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListUserOptions, UserList>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateUser updates a User
     *
     * @generated from protobuf rpc: UpdateUser
     */
    updateUser(input: User, options?: RpcOptions): UnaryCall<User, User> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<User, User>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteUser deletes a User
     *
     * @generated from protobuf rpc: DeleteUser
     */
    deleteUser(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * GetUser retrieves a specific User
     *
     * @generated from protobuf rpc: GetUser
     */
    getUser(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, User> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, User>("unary", this._transport, method, opt, input);
    }
    /**
     * CreateNamespace creates a Namespace
     *
     * @generated from protobuf rpc: CreateNamespace
     */
    createNamespace(input: Namespace, options?: RpcOptions): UnaryCall<Namespace, Namespace> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<Namespace, Namespace>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateNamespace updates a Namespace
     *
     * @generated from protobuf rpc: UpdateNamespace
     */
    updateNamespace(input: Namespace, options?: RpcOptions): UnaryCall<Namespace, Namespace> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<Namespace, Namespace>("unary", this._transport, method, opt, input);
    }
    /**
     * ListNamespace lists Namespaces
     *
     * @generated from protobuf rpc: ListNamespace
     */
    listNamespace(input: ListNamespaceOptions, options?: RpcOptions): UnaryCall<ListNamespaceOptions, NamespaceList> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListNamespaceOptions, NamespaceList>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteNamespace deletes a Namespace
     *
     * @generated from protobuf rpc: DeleteNamespace
     */
    deleteNamespace(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * GetNamespace retrieves a specific Namespace
     *
     * @generated from protobuf rpc: GetNamespace
     */
    getNamespace(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Namespace> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Namespace>("unary", this._transport, method, opt, input);
    }
    /**
     * CreateService creates a Service
     *
     * @generated from protobuf rpc: CreateService
     */
    createService(input: Service, options?: RpcOptions): UnaryCall<Service, Service> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<Service, Service>("unary", this._transport, method, opt, input);
    }
    /**
     * ListService lists Services
     *
     * @generated from protobuf rpc: ListService
     */
    listService(input: ListServiceOptions, options?: RpcOptions): UnaryCall<ListServiceOptions, ServiceList> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListServiceOptions, ServiceList>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateService updates a Service
     *
     * @generated from protobuf rpc: UpdateService
     */
    updateService(input: Service, options?: RpcOptions): UnaryCall<Service, Service> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<Service, Service>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteService deletes a Service
     *
     * @generated from protobuf rpc: DeleteService
     */
    deleteService(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * GetService retrieves a specific Service
     *
     * @generated from protobuf rpc: GetService
     */
    getService(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Service> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Service>("unary", this._transport, method, opt, input);
    }
    /**
     * ListSession lists Sessions
     *
     * @generated from protobuf rpc: ListSession
     */
    listSession(input: ListSessionOptions, options?: RpcOptions): UnaryCall<ListSessionOptions, SessionList> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSessionOptions, SessionList>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteSession deletes a Session
     *
     * @generated from protobuf rpc: DeleteSession
     */
    deleteSession(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * GetSession retrieves a specific Session
     *
     * @generated from protobuf rpc: GetSession
     */
    getSession(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Session> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Session>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateSession updates a Session
     *
     * @generated from protobuf rpc: UpdateSession
     */
    updateSession(input: Session, options?: RpcOptions): UnaryCall<Session, Session> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<Session, Session>("unary", this._transport, method, opt, input);
    }
    /**
     * CreateSecret creates a Secret
     *
     * @generated from protobuf rpc: CreateSecret
     */
    createSecret(input: Secret, options?: RpcOptions): UnaryCall<Secret, Secret> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<Secret, Secret>("unary", this._transport, method, opt, input);
    }
    /**
     * ListSecret lists Secrets
     *
     * @generated from protobuf rpc: ListSecret
     */
    listSecret(input: ListSecretOptions, options?: RpcOptions): UnaryCall<ListSecretOptions, SecretList> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSecretOptions, SecretList>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteSecret deletes a Secret
     *
     * @generated from protobuf rpc: DeleteSecret
     */
    deleteSecret(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[26], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * GetSecret retrieves a specific Secret
     *
     * @generated from protobuf rpc: GetSecret
     */
    getSecret(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Secret> {
        const method = this.methods[27], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Secret>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateSecret creates a Secret
     *
     * @generated from protobuf rpc: UpdateSecret
     */
    updateSecret(input: Secret, options?: RpcOptions): UnaryCall<Secret, Secret> {
        const method = this.methods[28], opt = this._transport.mergeOptions(options);
        return stackIntercept<Secret, Secret>("unary", this._transport, method, opt, input);
    }
    /**
     * CreateGroup creates a Group
     *
     * @generated from protobuf rpc: CreateGroup
     */
    createGroup(input: Group, options?: RpcOptions): UnaryCall<Group, Group> {
        const method = this.methods[29], opt = this._transport.mergeOptions(options);
        return stackIntercept<Group, Group>("unary", this._transport, method, opt, input);
    }
    /**
     * ListGroup lists Groups
     *
     * @generated from protobuf rpc: ListGroup
     */
    listGroup(input: ListGroupOptions, options?: RpcOptions): UnaryCall<ListGroupOptions, GroupList> {
        const method = this.methods[30], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListGroupOptions, GroupList>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateGroup updates a Group
     *
     * @generated from protobuf rpc: UpdateGroup
     */
    updateGroup(input: Group, options?: RpcOptions): UnaryCall<Group, Group> {
        const method = this.methods[31], opt = this._transport.mergeOptions(options);
        return stackIntercept<Group, Group>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteGroup deletes a Group
     *
     * @generated from protobuf rpc: DeleteGroup
     */
    deleteGroup(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[32], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * GetGroup retrieves a specific Group
     *
     * @generated from protobuf rpc: GetGroup
     */
    getGroup(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Group> {
        const method = this.methods[33], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Group>("unary", this._transport, method, opt, input);
    }
    /**
     * ListDevice lists Devices
     *
     * @generated from protobuf rpc: ListDevice
     */
    listDevice(input: ListDeviceOptions, options?: RpcOptions): UnaryCall<ListDeviceOptions, DeviceList> {
        const method = this.methods[34], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDeviceOptions, DeviceList>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteDevice deletes a Device
     *
     * @generated from protobuf rpc: DeleteDevice
     */
    deleteDevice(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[35], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * GetDevice retrieves a specific Device
     *
     * @generated from protobuf rpc: GetDevice
     */
    getDevice(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Device> {
        const method = this.methods[36], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Device>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateDevice updates a Device
     *
     * @generated from protobuf rpc: UpdateDevice
     */
    updateDevice(input: Device, options?: RpcOptions): UnaryCall<Device, Device> {
        const method = this.methods[37], opt = this._transport.mergeOptions(options);
        return stackIntercept<Device, Device>("unary", this._transport, method, opt, input);
    }
    /**
     * CreateCredential creates a Credential
     *
     * @generated from protobuf rpc: CreateCredential
     */
    createCredential(input: Credential, options?: RpcOptions): UnaryCall<Credential, Credential> {
        const method = this.methods[38], opt = this._transport.mergeOptions(options);
        return stackIntercept<Credential, Credential>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateCredential creates a Credential
     *
     * @generated from protobuf rpc: UpdateCredential
     */
    updateCredential(input: Credential, options?: RpcOptions): UnaryCall<Credential, Credential> {
        const method = this.methods[39], opt = this._transport.mergeOptions(options);
        return stackIntercept<Credential, Credential>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteCredential deletes a Credential
     *
     * @generated from protobuf rpc: DeleteCredential
     */
    deleteCredential(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[40], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * ListCredential lists Credentials
     *
     * @generated from protobuf rpc: ListCredential
     */
    listCredential(input: ListCredentialOptions, options?: RpcOptions): UnaryCall<ListCredentialOptions, CredentialList> {
        const method = this.methods[41], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListCredentialOptions, CredentialList>("unary", this._transport, method, opt, input);
    }
    /**
     * GetCredential retrieves a specific Credential
     *
     * @generated from protobuf rpc: GetCredential
     */
    getCredential(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Credential> {
        const method = this.methods[42], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Credential>("unary", this._transport, method, opt, input);
    }
    /**
     * GenerateCredentialToken generates/rotates a Credential token
     *
     * @generated from protobuf rpc: GenerateCredentialToken
     */
    generateCredentialToken(input: GenerateCredentialTokenRequest, options?: RpcOptions): UnaryCall<GenerateCredentialTokenRequest, CredentialToken> {
        const method = this.methods[43], opt = this._transport.mergeOptions(options);
        return stackIntercept<GenerateCredentialTokenRequest, CredentialToken>("unary", this._transport, method, opt, input);
    }
    /**
     * CreateIdentityProvider creates an IdentityProvider
     *
     * @generated from protobuf rpc: CreateIdentityProvider
     */
    createIdentityProvider(input: IdentityProvider, options?: RpcOptions): UnaryCall<IdentityProvider, IdentityProvider> {
        const method = this.methods[44], opt = this._transport.mergeOptions(options);
        return stackIntercept<IdentityProvider, IdentityProvider>("unary", this._transport, method, opt, input);
    }
    /**
     * GetIdentityProvider retrieves a specific IdentityProvider
     *
     * @generated from protobuf rpc: GetIdentityProvider
     */
    getIdentityProvider(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, IdentityProvider> {
        const method = this.methods[45], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, IdentityProvider>("unary", this._transport, method, opt, input);
    }
    /**
     * ListIdentityProvider lists IdentityProviders
     *
     * @generated from protobuf rpc: ListIdentityProvider
     */
    listIdentityProvider(input: ListIdentityProviderOptions, options?: RpcOptions): UnaryCall<ListIdentityProviderOptions, IdentityProviderList> {
        const method = this.methods[46], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListIdentityProviderOptions, IdentityProviderList>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateIdentityProvider updates an UpdateIdentityProvider
     *
     * @generated from protobuf rpc: UpdateIdentityProvider
     */
    updateIdentityProvider(input: IdentityProvider, options?: RpcOptions): UnaryCall<IdentityProvider, IdentityProvider> {
        const method = this.methods[47], opt = this._transport.mergeOptions(options);
        return stackIntercept<IdentityProvider, IdentityProvider>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteIdentityProvider deletes an IdentityProvider
     *
     * @generated from protobuf rpc: DeleteIdentityProvider
     */
    deleteIdentityProvider(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[48], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * GetRegion retrieves a specific Region
     *
     * @generated from protobuf rpc: GetRegion
     */
    getRegion(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Region> {
        const method = this.methods[49], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Region>("unary", this._transport, method, opt, input);
    }
    /**
     * ListRegion lists Regions
     *
     * @generated from protobuf rpc: ListRegion
     */
    listRegion(input: ListRegionOptions, options?: RpcOptions): UnaryCall<ListRegionOptions, RegionList> {
        const method = this.methods[50], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListRegionOptions, RegionList>("unary", this._transport, method, opt, input);
    }
    /**
     * ListGateway lists Gateways
     *
     * @generated from protobuf rpc: ListGateway
     */
    listGateway(input: ListGatewayOptions, options?: RpcOptions): UnaryCall<ListGatewayOptions, GatewayList> {
        const method = this.methods[51], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListGatewayOptions, GatewayList>("unary", this._transport, method, opt, input);
    }
    /**
     * GetGateway retrieves a specific Gateway
     *
     * @generated from protobuf rpc: GetGateway
     */
    getGateway(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Gateway> {
        const method = this.methods[52], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Gateway>("unary", this._transport, method, opt, input);
    }
    /**
     * GetClusterConfig gets the Cluster Configuration.
     *
     * @generated from protobuf rpc: GetClusterConfig
     */
    getClusterConfig(input: GetClusterConfigRequest, options?: RpcOptions): UnaryCall<GetClusterConfigRequest, ClusterConfig> {
        const method = this.methods[53], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetClusterConfigRequest, ClusterConfig>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateConfig updates the Cluster Configuration.
     *
     * @generated from protobuf rpc: UpdateClusterConfig
     */
    updateClusterConfig(input: ClusterConfig, options?: RpcOptions): UnaryCall<ClusterConfig, ClusterConfig> {
        const method = this.methods[54], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClusterConfig, ClusterConfig>("unary", this._transport, method, opt, input);
    }
    /**
     * ListAuthenticator lists Authenticators
     *
     * @generated from protobuf rpc: ListAuthenticator
     */
    listAuthenticator(input: ListAuthenticatorOptions, options?: RpcOptions): UnaryCall<ListAuthenticatorOptions, AuthenticatorList> {
        const method = this.methods[55], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAuthenticatorOptions, AuthenticatorList>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteAuthenticator deletes an Authenticator
     *
     * @generated from protobuf rpc: DeleteAuthenticator
     */
    deleteAuthenticator(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[56], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * GetAuthenticator retrieves a specific Authenticator
     *
     * @generated from protobuf rpc: GetAuthenticator
     */
    getAuthenticator(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Authenticator> {
        const method = this.methods[57], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Authenticator>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateAuthenticator updates an Authenticator
     *
     * @generated from protobuf rpc: UpdateAuthenticator
     */
    updateAuthenticator(input: Authenticator, options?: RpcOptions): UnaryCall<Authenticator, Authenticator> {
        const method = this.methods[58], opt = this._transport.mergeOptions(options);
        return stackIntercept<Authenticator, Authenticator>("unary", this._transport, method, opt, input);
    }
    /**
     * CreateConfig creates a Config
     *
     * @generated from protobuf rpc: CreateConfig
     */
    createConfig(input: Config, options?: RpcOptions): UnaryCall<Config, Config> {
        const method = this.methods[59], opt = this._transport.mergeOptions(options);
        return stackIntercept<Config, Config>("unary", this._transport, method, opt, input);
    }
    /**
     * ListConfig lists Configs
     *
     * @generated from protobuf rpc: ListConfig
     */
    listConfig(input: ListConfigOptions, options?: RpcOptions): UnaryCall<ListConfigOptions, ConfigList> {
        const method = this.methods[60], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListConfigOptions, ConfigList>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateConfig updates a Config
     *
     * @generated from protobuf rpc: UpdateConfig
     */
    updateConfig(input: Config, options?: RpcOptions): UnaryCall<Config, Config> {
        const method = this.methods[61], opt = this._transport.mergeOptions(options);
        return stackIntercept<Config, Config>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteConfig deletes a Config
     *
     * @generated from protobuf rpc: DeleteConfig
     */
    deleteConfig(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[62], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * GetConfig retrieves a specific Config
     *
     * @generated from protobuf rpc: GetConfig
     */
    getConfig(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Config> {
        const method = this.methods[63], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Config>("unary", this._transport, method, opt, input);
    }
}
