// @generated by protobuf-ts 2.11.1 with parameter long_type_number
// @generated from protobuf file "apis/protobuf/main/cordiumv1/cordiumv1.proto" (package "octelium.api.main.cordium.v1", syntax proto3)
// tslint:disable
//
//
// Copyright (c) 2020-present Octelium. All rights reserved.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License version 3,
// as published by the Free Software Foundation of the License.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
import { ManagementService } from "./cordiumv1.js";
import type { ClusterConfig } from "./cordiumv1.js";
import type { GetClusterConfigRequest } from "./cordiumv1.js";
import { WorkspaceService } from "./cordiumv1.js";
import type { ExecResponse } from "./cordiumv1.js";
import type { ExecRequest } from "./cordiumv1.js";
import type { DuplexStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { ListenLogResponse } from "./cordiumv1.js";
import type { ListenLogRequest } from "./cordiumv1.js";
import type { ListenTerminalResponse } from "./cordiumv1.js";
import type { ListenTerminalRequest } from "./cordiumv1.js";
import type { SetTerminalWindowSizeResponse } from "./cordiumv1.js";
import type { SetTerminalWindowSizeRequest } from "./cordiumv1.js";
import type { WriteTerminalDataResponse } from "./cordiumv1.js";
import type { WriteTerminalDataRequest } from "./cordiumv1.js";
import type { ListTerminalResponse } from "./cordiumv1.js";
import type { ListTerminalRequest } from "./cordiumv1.js";
import type { RemoveTerminalResponse } from "./cordiumv1.js";
import type { RemoveTerminalRequest } from "./cordiumv1.js";
import type { CreateTerminalResponse } from "./cordiumv1.js";
import type { CreateTerminalRequest } from "./cordiumv1.js";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MainService } from "./cordiumv1.js";
import type { WatchWorkspaceResponse } from "./cordiumv1.js";
import type { WatchWorkspaceRequest } from "./cordiumv1.js";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RegionList } from "./cordiumv1.js";
import type { ListRegionOptions } from "./cordiumv1.js";
import type { UserConfig } from "./cordiumv1.js";
import type { GetUserConfigRequest } from "./cordiumv1.js";
import type { UserSecretList } from "./cordiumv1.js";
import type { ListUserSecretOptions } from "./cordiumv1.js";
import type { UserSecret } from "./cordiumv1.js";
import type { LeaveSpaceResponse } from "./cordiumv1.js";
import type { LeaveSpaceRequest } from "./cordiumv1.js";
import type { GitProviderList } from "./cordiumv1.js";
import type { ListGitProviderOptions } from "./cordiumv1.js";
import type { MembershipList } from "./cordiumv1.js";
import type { ListMembershipOptions } from "./cordiumv1.js";
import type { TemplateList } from "./cordiumv1.js";
import type { ListTemplateOptions } from "./cordiumv1.js";
import type { SpaceList } from "./cordiumv1.js";
import type { ListSpaceOptions } from "./cordiumv1.js";
import type { UnshareWorkspacePortResponse } from "./cordiumv1.js";
import type { UnshareWorkspacePortRequest } from "./cordiumv1.js";
import type { ShareWorkspacePortResponse } from "./cordiumv1.js";
import type { ShareWorkspacePortRequest } from "./cordiumv1.js";
import type { StopWorkspaceResponse } from "./cordiumv1.js";
import type { StopWorkspaceRequest } from "./cordiumv1.js";
import type { StartWorkspaceResponse } from "./cordiumv1.js";
import type { StartWorkspaceRequest } from "./cordiumv1.js";
import type { WorkspaceList } from "./cordiumv1.js";
import type { ListWorkspaceOptions } from "./cordiumv1.js";
import type { Workspace } from "./cordiumv1.js";
import type { GitProvider } from "./cordiumv1.js";
import type { GetSpaceMembershipRequest } from "./cordiumv1.js";
import type { Membership } from "./cordiumv1.js";
import type { CreateMembershipRequest } from "./cordiumv1.js";
import type { Space } from "./cordiumv1.js";
import type { CancelBuildTemplateRequest } from "./cordiumv1.js";
import type { BuildTemplateRequest } from "./cordiumv1.js";
import type { Template } from "./cordiumv1.js";
import type { GetOptions } from "../metav1/metav1.js";
import type { OperationResult } from "../metav1/metav1.js";
import type { DeleteOptions } from "../metav1/metav1.js";
import type { SecretList } from "./cordiumv1.js";
import type { ListSecretOptions } from "./cordiumv1.js";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Secret } from "./cordiumv1.js";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service octelium.api.main.cordium.v1.MainService
 */
export interface IMainServiceClient {
    /**
     * CreateSecret creates a Secret
     *
     * @generated from protobuf rpc: CreateSecret
     */
    createSecret(input: Secret, options?: RpcOptions): UnaryCall<Secret, Secret>;
    /**
     * ListSecret lists Secrets
     *
     * @generated from protobuf rpc: ListSecret
     */
    listSecret(input: ListSecretOptions, options?: RpcOptions): UnaryCall<ListSecretOptions, SecretList>;
    /**
     * DeleteWorkspace deletes a Workspace
     *
     * @generated from protobuf rpc: DeleteSecret
     */
    deleteSecret(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * GetWorkspace retrieves a specific Workspace
     *
     * @generated from protobuf rpc: GetSecret
     */
    getSecret(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Secret>;
    /**
     * CreateTemplate creates a Template owned by the User.
     *
     * @generated from protobuf rpc: CreateTemplate
     */
    createTemplate(input: Template, options?: RpcOptions): UnaryCall<Template, Template>;
    /**
     * UpdateTemplate updates a Template owned by the User.
     *
     * @generated from protobuf rpc: UpdateTemplate
     */
    updateTemplate(input: Template, options?: RpcOptions): UnaryCall<Template, Template>;
    /**
     * DeleteTemplate deletes a Template owned by the User.
     *
     * @generated from protobuf rpc: DeleteTemplate
     */
    deleteTemplate(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * @generated from protobuf rpc: BuildTemplate
     */
    buildTemplate(input: BuildTemplateRequest, options?: RpcOptions): UnaryCall<BuildTemplateRequest, Template>;
    /**
     * @generated from protobuf rpc: CancelBuildTemplate
     */
    cancelBuildTemplate(input: CancelBuildTemplateRequest, options?: RpcOptions): UnaryCall<CancelBuildTemplateRequest, Template>;
    /**
     * CreateTemplate creates a Template owned by the User.
     *
     * @generated from protobuf rpc: CreateSpace
     */
    createSpace(input: Space, options?: RpcOptions): UnaryCall<Space, Space>;
    /**
     * UpdateTemplate updates a Template owned by the User.
     *
     * @generated from protobuf rpc: UpdateSpace
     */
    updateSpace(input: Space, options?: RpcOptions): UnaryCall<Space, Space>;
    /**
     * DeleteTemplate deletes a Template owned by the User.
     *
     * @generated from protobuf rpc: DeleteSpace
     */
    deleteSpace(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * @generated from protobuf rpc: CreateMembership
     */
    createMembership(input: CreateMembershipRequest, options?: RpcOptions): UnaryCall<CreateMembershipRequest, Membership>;
    /**
     * @generated from protobuf rpc: DeleteMembership
     */
    deleteMembership(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * @generated from protobuf rpc: GetSpaceMembership
     */
    getSpaceMembership(input: GetSpaceMembershipRequest, options?: RpcOptions): UnaryCall<GetSpaceMembershipRequest, Membership>;
    /**
     * @generated from protobuf rpc: UpdateMembership
     */
    updateMembership(input: Membership, options?: RpcOptions): UnaryCall<Membership, Membership>;
    /**
     * @generated from protobuf rpc: CreateGitProvider
     */
    createGitProvider(input: GitProvider, options?: RpcOptions): UnaryCall<GitProvider, GitProvider>;
    /**
     * @generated from protobuf rpc: UpdateGitProvider
     */
    updateGitProvider(input: GitProvider, options?: RpcOptions): UnaryCall<GitProvider, GitProvider>;
    /**
     * @generated from protobuf rpc: DeleteGitProvider
     */
    deleteGitProvider(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * CreateWorkspace creates a Workspace owned by the User.
     *
     * @generated from protobuf rpc: CreateWorkspace
     */
    createWorkspace(input: Workspace, options?: RpcOptions): UnaryCall<Workspace, Workspace>;
    /**
     * UpdateWorkspace updates a Workspace owned by the User.
     *
     * @generated from protobuf rpc: UpdateWorkspace
     */
    updateWorkspace(input: Workspace, options?: RpcOptions): UnaryCall<Workspace, Workspace>;
    /**
     * DeleteWorkspace deletes a Workspace owned by the User.
     *
     * @generated from protobuf rpc: DeleteWorkspace
     */
    deleteWorkspace(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * ListWorkspace lists the Workspaces owned by the User.
     *
     * @generated from protobuf rpc: ListWorkspace
     */
    listWorkspace(input: ListWorkspaceOptions, options?: RpcOptions): UnaryCall<ListWorkspaceOptions, WorkspaceList>;
    /**
     * @generated from protobuf rpc: StartWorkspace
     */
    startWorkspace(input: StartWorkspaceRequest, options?: RpcOptions): UnaryCall<StartWorkspaceRequest, StartWorkspaceResponse>;
    /**
     * @generated from protobuf rpc: StopWorkspace
     */
    stopWorkspace(input: StopWorkspaceRequest, options?: RpcOptions): UnaryCall<StopWorkspaceRequest, StopWorkspaceResponse>;
    /**
     * @generated from protobuf rpc: ShareWorkspacePort
     */
    shareWorkspacePort(input: ShareWorkspacePortRequest, options?: RpcOptions): UnaryCall<ShareWorkspacePortRequest, ShareWorkspacePortResponse>;
    /**
     * @generated from protobuf rpc: UnshareWorkspacePort
     */
    unshareWorkspacePort(input: UnshareWorkspacePortRequest, options?: RpcOptions): UnaryCall<UnshareWorkspacePortRequest, UnshareWorkspacePortResponse>;
    /**
     * @generated from protobuf rpc: ListSpace
     */
    listSpace(input: ListSpaceOptions, options?: RpcOptions): UnaryCall<ListSpaceOptions, SpaceList>;
    /**
     * @generated from protobuf rpc: ListTemplate
     */
    listTemplate(input: ListTemplateOptions, options?: RpcOptions): UnaryCall<ListTemplateOptions, TemplateList>;
    /**
     * @generated from protobuf rpc: ListMembership
     */
    listMembership(input: ListMembershipOptions, options?: RpcOptions): UnaryCall<ListMembershipOptions, MembershipList>;
    /**
     * @generated from protobuf rpc: ListGitProvider
     */
    listGitProvider(input: ListGitProviderOptions, options?: RpcOptions): UnaryCall<ListGitProviderOptions, GitProviderList>;
    /**
     * @generated from protobuf rpc: GetSpace
     */
    getSpace(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Space>;
    /**
     * @generated from protobuf rpc: GetWorkspace
     */
    getWorkspace(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Workspace>;
    /**
     * @generated from protobuf rpc: GetTemplate
     */
    getTemplate(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Template>;
    /**
     * @generated from protobuf rpc: GetGitProvider
     */
    getGitProvider(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, GitProvider>;
    /**
     * @generated from protobuf rpc: GetMembership
     */
    getMembership(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Membership>;
    /**
     * @generated from protobuf rpc: LeaveSpace
     */
    leaveSpace(input: LeaveSpaceRequest, options?: RpcOptions): UnaryCall<LeaveSpaceRequest, LeaveSpaceResponse>;
    /**
     * CreateWorkspace creates a Workspace owned by the User.
     *
     * @generated from protobuf rpc: CreateUserSecret
     */
    createUserSecret(input: UserSecret, options?: RpcOptions): UnaryCall<UserSecret, UserSecret>;
    /**
     * UpdateWorkspace updates a Workspace owned by the User.
     *
     * @generated from protobuf rpc: UpdateUserSecret
     */
    updateUserSecret(input: UserSecret, options?: RpcOptions): UnaryCall<UserSecret, UserSecret>;
    /**
     * DeleteWorkspace deletes a Workspace owned by the User.
     *
     * @generated from protobuf rpc: DeleteUserSecret
     */
    deleteUserSecret(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * ListWorkspace lists the Workspaces owned by the User.
     *
     * @generated from protobuf rpc: ListUserSecret
     */
    listUserSecret(input: ListUserSecretOptions, options?: RpcOptions): UnaryCall<ListUserSecretOptions, UserSecretList>;
    /**
     * @generated from protobuf rpc: GetUserSecret
     */
    getUserSecret(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, UserSecret>;
    /**
     * @generated from protobuf rpc: GetUserConfig
     */
    getUserConfig(input: GetUserConfigRequest, options?: RpcOptions): UnaryCall<GetUserConfigRequest, UserConfig>;
    /**
     * @generated from protobuf rpc: UpdateUserConfig
     */
    updateUserConfig(input: UserConfig, options?: RpcOptions): UnaryCall<UserConfig, UserConfig>;
    /**
     * @generated from protobuf rpc: ListRegion
     */
    listRegion(input: ListRegionOptions, options?: RpcOptions): UnaryCall<ListRegionOptions, RegionList>;
    /**
     * @generated from protobuf rpc: WatchWorkspace
     */
    watchWorkspace(input: WatchWorkspaceRequest, options?: RpcOptions): ServerStreamingCall<WatchWorkspaceRequest, WatchWorkspaceResponse>;
}
/**
 * @generated from protobuf service octelium.api.main.cordium.v1.MainService
 */
export class MainServiceClient implements IMainServiceClient, ServiceInfo {
    typeName = MainService.typeName;
    methods = MainService.methods;
    options = MainService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * CreateSecret creates a Secret
     *
     * @generated from protobuf rpc: CreateSecret
     */
    createSecret(input: Secret, options?: RpcOptions): UnaryCall<Secret, Secret> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Secret, Secret>("unary", this._transport, method, opt, input);
    }
    /**
     * ListSecret lists Secrets
     *
     * @generated from protobuf rpc: ListSecret
     */
    listSecret(input: ListSecretOptions, options?: RpcOptions): UnaryCall<ListSecretOptions, SecretList> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSecretOptions, SecretList>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteWorkspace deletes a Workspace
     *
     * @generated from protobuf rpc: DeleteSecret
     */
    deleteSecret(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * GetWorkspace retrieves a specific Workspace
     *
     * @generated from protobuf rpc: GetSecret
     */
    getSecret(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Secret> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Secret>("unary", this._transport, method, opt, input);
    }
    /**
     * CreateTemplate creates a Template owned by the User.
     *
     * @generated from protobuf rpc: CreateTemplate
     */
    createTemplate(input: Template, options?: RpcOptions): UnaryCall<Template, Template> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<Template, Template>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateTemplate updates a Template owned by the User.
     *
     * @generated from protobuf rpc: UpdateTemplate
     */
    updateTemplate(input: Template, options?: RpcOptions): UnaryCall<Template, Template> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<Template, Template>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteTemplate deletes a Template owned by the User.
     *
     * @generated from protobuf rpc: DeleteTemplate
     */
    deleteTemplate(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: BuildTemplate
     */
    buildTemplate(input: BuildTemplateRequest, options?: RpcOptions): UnaryCall<BuildTemplateRequest, Template> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<BuildTemplateRequest, Template>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CancelBuildTemplate
     */
    cancelBuildTemplate(input: CancelBuildTemplateRequest, options?: RpcOptions): UnaryCall<CancelBuildTemplateRequest, Template> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<CancelBuildTemplateRequest, Template>("unary", this._transport, method, opt, input);
    }
    /**
     * CreateTemplate creates a Template owned by the User.
     *
     * @generated from protobuf rpc: CreateSpace
     */
    createSpace(input: Space, options?: RpcOptions): UnaryCall<Space, Space> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<Space, Space>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateTemplate updates a Template owned by the User.
     *
     * @generated from protobuf rpc: UpdateSpace
     */
    updateSpace(input: Space, options?: RpcOptions): UnaryCall<Space, Space> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<Space, Space>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteTemplate deletes a Template owned by the User.
     *
     * @generated from protobuf rpc: DeleteSpace
     */
    deleteSpace(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateMembership
     */
    createMembership(input: CreateMembershipRequest, options?: RpcOptions): UnaryCall<CreateMembershipRequest, Membership> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateMembershipRequest, Membership>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteMembership
     */
    deleteMembership(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSpaceMembership
     */
    getSpaceMembership(input: GetSpaceMembershipRequest, options?: RpcOptions): UnaryCall<GetSpaceMembershipRequest, Membership> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSpaceMembershipRequest, Membership>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateMembership
     */
    updateMembership(input: Membership, options?: RpcOptions): UnaryCall<Membership, Membership> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<Membership, Membership>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateGitProvider
     */
    createGitProvider(input: GitProvider, options?: RpcOptions): UnaryCall<GitProvider, GitProvider> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<GitProvider, GitProvider>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateGitProvider
     */
    updateGitProvider(input: GitProvider, options?: RpcOptions): UnaryCall<GitProvider, GitProvider> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<GitProvider, GitProvider>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteGitProvider
     */
    deleteGitProvider(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * CreateWorkspace creates a Workspace owned by the User.
     *
     * @generated from protobuf rpc: CreateWorkspace
     */
    createWorkspace(input: Workspace, options?: RpcOptions): UnaryCall<Workspace, Workspace> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<Workspace, Workspace>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateWorkspace updates a Workspace owned by the User.
     *
     * @generated from protobuf rpc: UpdateWorkspace
     */
    updateWorkspace(input: Workspace, options?: RpcOptions): UnaryCall<Workspace, Workspace> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<Workspace, Workspace>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteWorkspace deletes a Workspace owned by the User.
     *
     * @generated from protobuf rpc: DeleteWorkspace
     */
    deleteWorkspace(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * ListWorkspace lists the Workspaces owned by the User.
     *
     * @generated from protobuf rpc: ListWorkspace
     */
    listWorkspace(input: ListWorkspaceOptions, options?: RpcOptions): UnaryCall<ListWorkspaceOptions, WorkspaceList> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListWorkspaceOptions, WorkspaceList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: StartWorkspace
     */
    startWorkspace(input: StartWorkspaceRequest, options?: RpcOptions): UnaryCall<StartWorkspaceRequest, StartWorkspaceResponse> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<StartWorkspaceRequest, StartWorkspaceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: StopWorkspace
     */
    stopWorkspace(input: StopWorkspaceRequest, options?: RpcOptions): UnaryCall<StopWorkspaceRequest, StopWorkspaceResponse> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<StopWorkspaceRequest, StopWorkspaceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ShareWorkspacePort
     */
    shareWorkspacePort(input: ShareWorkspacePortRequest, options?: RpcOptions): UnaryCall<ShareWorkspacePortRequest, ShareWorkspacePortResponse> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<ShareWorkspacePortRequest, ShareWorkspacePortResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UnshareWorkspacePort
     */
    unshareWorkspacePort(input: UnshareWorkspacePortRequest, options?: RpcOptions): UnaryCall<UnshareWorkspacePortRequest, UnshareWorkspacePortResponse> {
        const method = this.methods[26], opt = this._transport.mergeOptions(options);
        return stackIntercept<UnshareWorkspacePortRequest, UnshareWorkspacePortResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListSpace
     */
    listSpace(input: ListSpaceOptions, options?: RpcOptions): UnaryCall<ListSpaceOptions, SpaceList> {
        const method = this.methods[27], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSpaceOptions, SpaceList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListTemplate
     */
    listTemplate(input: ListTemplateOptions, options?: RpcOptions): UnaryCall<ListTemplateOptions, TemplateList> {
        const method = this.methods[28], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListTemplateOptions, TemplateList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListMembership
     */
    listMembership(input: ListMembershipOptions, options?: RpcOptions): UnaryCall<ListMembershipOptions, MembershipList> {
        const method = this.methods[29], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListMembershipOptions, MembershipList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListGitProvider
     */
    listGitProvider(input: ListGitProviderOptions, options?: RpcOptions): UnaryCall<ListGitProviderOptions, GitProviderList> {
        const method = this.methods[30], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListGitProviderOptions, GitProviderList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSpace
     */
    getSpace(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Space> {
        const method = this.methods[31], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Space>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetWorkspace
     */
    getWorkspace(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Workspace> {
        const method = this.methods[32], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Workspace>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTemplate
     */
    getTemplate(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Template> {
        const method = this.methods[33], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Template>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetGitProvider
     */
    getGitProvider(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, GitProvider> {
        const method = this.methods[34], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, GitProvider>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMembership
     */
    getMembership(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Membership> {
        const method = this.methods[35], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Membership>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LeaveSpace
     */
    leaveSpace(input: LeaveSpaceRequest, options?: RpcOptions): UnaryCall<LeaveSpaceRequest, LeaveSpaceResponse> {
        const method = this.methods[36], opt = this._transport.mergeOptions(options);
        return stackIntercept<LeaveSpaceRequest, LeaveSpaceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * CreateWorkspace creates a Workspace owned by the User.
     *
     * @generated from protobuf rpc: CreateUserSecret
     */
    createUserSecret(input: UserSecret, options?: RpcOptions): UnaryCall<UserSecret, UserSecret> {
        const method = this.methods[37], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserSecret, UserSecret>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateWorkspace updates a Workspace owned by the User.
     *
     * @generated from protobuf rpc: UpdateUserSecret
     */
    updateUserSecret(input: UserSecret, options?: RpcOptions): UnaryCall<UserSecret, UserSecret> {
        const method = this.methods[38], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserSecret, UserSecret>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteWorkspace deletes a Workspace owned by the User.
     *
     * @generated from protobuf rpc: DeleteUserSecret
     */
    deleteUserSecret(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[39], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * ListWorkspace lists the Workspaces owned by the User.
     *
     * @generated from protobuf rpc: ListUserSecret
     */
    listUserSecret(input: ListUserSecretOptions, options?: RpcOptions): UnaryCall<ListUserSecretOptions, UserSecretList> {
        const method = this.methods[40], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListUserSecretOptions, UserSecretList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUserSecret
     */
    getUserSecret(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, UserSecret> {
        const method = this.methods[41], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, UserSecret>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUserConfig
     */
    getUserConfig(input: GetUserConfigRequest, options?: RpcOptions): UnaryCall<GetUserConfigRequest, UserConfig> {
        const method = this.methods[42], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserConfigRequest, UserConfig>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateUserConfig
     */
    updateUserConfig(input: UserConfig, options?: RpcOptions): UnaryCall<UserConfig, UserConfig> {
        const method = this.methods[43], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserConfig, UserConfig>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListRegion
     */
    listRegion(input: ListRegionOptions, options?: RpcOptions): UnaryCall<ListRegionOptions, RegionList> {
        const method = this.methods[44], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListRegionOptions, RegionList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: WatchWorkspace
     */
    watchWorkspace(input: WatchWorkspaceRequest, options?: RpcOptions): ServerStreamingCall<WatchWorkspaceRequest, WatchWorkspaceResponse> {
        const method = this.methods[45], opt = this._transport.mergeOptions(options);
        return stackIntercept<WatchWorkspaceRequest, WatchWorkspaceResponse>("serverStreaming", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service octelium.api.main.cordium.v1.WorkspaceService
 */
export interface IWorkspaceServiceClient {
    /**
     * @generated from protobuf rpc: CreateTerminal
     */
    createTerminal(input: CreateTerminalRequest, options?: RpcOptions): UnaryCall<CreateTerminalRequest, CreateTerminalResponse>;
    /**
     * @generated from protobuf rpc: RemoveTerminal
     */
    removeTerminal(input: RemoveTerminalRequest, options?: RpcOptions): UnaryCall<RemoveTerminalRequest, RemoveTerminalResponse>;
    /**
     * @generated from protobuf rpc: ListTerminal
     */
    listTerminal(input: ListTerminalRequest, options?: RpcOptions): UnaryCall<ListTerminalRequest, ListTerminalResponse>;
    /**
     * @generated from protobuf rpc: WriteTerminalData
     */
    writeTerminalData(input: WriteTerminalDataRequest, options?: RpcOptions): UnaryCall<WriteTerminalDataRequest, WriteTerminalDataResponse>;
    /**
     * @generated from protobuf rpc: SetTerminalWindowSize
     */
    setTerminalWindowSize(input: SetTerminalWindowSizeRequest, options?: RpcOptions): UnaryCall<SetTerminalWindowSizeRequest, SetTerminalWindowSizeResponse>;
    /**
     * @generated from protobuf rpc: ListenTerminal
     */
    listenTerminal(input: ListenTerminalRequest, options?: RpcOptions): ServerStreamingCall<ListenTerminalRequest, ListenTerminalResponse>;
    /**
     * @generated from protobuf rpc: ListenLog
     */
    listenLog(input: ListenLogRequest, options?: RpcOptions): ServerStreamingCall<ListenLogRequest, ListenLogResponse>;
    /**
     * @generated from protobuf rpc: Exec
     */
    exec(options?: RpcOptions): DuplexStreamingCall<ExecRequest, ExecResponse>;
}
/**
 * @generated from protobuf service octelium.api.main.cordium.v1.WorkspaceService
 */
export class WorkspaceServiceClient implements IWorkspaceServiceClient, ServiceInfo {
    typeName = WorkspaceService.typeName;
    methods = WorkspaceService.methods;
    options = WorkspaceService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateTerminal
     */
    createTerminal(input: CreateTerminalRequest, options?: RpcOptions): UnaryCall<CreateTerminalRequest, CreateTerminalResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateTerminalRequest, CreateTerminalResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveTerminal
     */
    removeTerminal(input: RemoveTerminalRequest, options?: RpcOptions): UnaryCall<RemoveTerminalRequest, RemoveTerminalResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveTerminalRequest, RemoveTerminalResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListTerminal
     */
    listTerminal(input: ListTerminalRequest, options?: RpcOptions): UnaryCall<ListTerminalRequest, ListTerminalResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListTerminalRequest, ListTerminalResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: WriteTerminalData
     */
    writeTerminalData(input: WriteTerminalDataRequest, options?: RpcOptions): UnaryCall<WriteTerminalDataRequest, WriteTerminalDataResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<WriteTerminalDataRequest, WriteTerminalDataResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetTerminalWindowSize
     */
    setTerminalWindowSize(input: SetTerminalWindowSizeRequest, options?: RpcOptions): UnaryCall<SetTerminalWindowSizeRequest, SetTerminalWindowSizeResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetTerminalWindowSizeRequest, SetTerminalWindowSizeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListenTerminal
     */
    listenTerminal(input: ListenTerminalRequest, options?: RpcOptions): ServerStreamingCall<ListenTerminalRequest, ListenTerminalResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListenTerminalRequest, ListenTerminalResponse>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListenLog
     */
    listenLog(input: ListenLogRequest, options?: RpcOptions): ServerStreamingCall<ListenLogRequest, ListenLogResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListenLogRequest, ListenLogResponse>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Exec
     */
    exec(options?: RpcOptions): DuplexStreamingCall<ExecRequest, ExecResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ExecRequest, ExecResponse>("duplex", this._transport, method, opt);
    }
}
/**
 * @generated from protobuf service octelium.api.main.cordium.v1.ManagementService
 */
export interface IManagementServiceClient {
    /**
     * GetClusterConfig gets the Cluster Configuration.
     *
     * @generated from protobuf rpc: GetClusterConfig
     */
    getClusterConfig(input: GetClusterConfigRequest, options?: RpcOptions): UnaryCall<GetClusterConfigRequest, ClusterConfig>;
    /**
     * UpdateConfig updates the Cluster Configuration.
     *
     * @generated from protobuf rpc: UpdateClusterConfig
     */
    updateClusterConfig(input: ClusterConfig, options?: RpcOptions): UnaryCall<ClusterConfig, ClusterConfig>;
}
/**
 * @generated from protobuf service octelium.api.main.cordium.v1.ManagementService
 */
export class ManagementServiceClient implements IManagementServiceClient, ServiceInfo {
    typeName = ManagementService.typeName;
    methods = ManagementService.methods;
    options = ManagementService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * GetClusterConfig gets the Cluster Configuration.
     *
     * @generated from protobuf rpc: GetClusterConfig
     */
    getClusterConfig(input: GetClusterConfigRequest, options?: RpcOptions): UnaryCall<GetClusterConfigRequest, ClusterConfig> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetClusterConfigRequest, ClusterConfig>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateConfig updates the Cluster Configuration.
     *
     * @generated from protobuf rpc: UpdateClusterConfig
     */
    updateClusterConfig(input: ClusterConfig, options?: RpcOptions): UnaryCall<ClusterConfig, ClusterConfig> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClusterConfig, ClusterConfig>("unary", this._transport, method, opt, input);
    }
}
