// @generated by protobuf-ts 2.11.1 with parameter long_type_number
// @generated from protobuf file "apis/protobuf/main/authv1/authv1.proto" (package "octelium.api.main.auth.v1", syntax proto3)
// tslint:disable
//
// Copyright Octelium Labs, LLC. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MainService } from "./authv1.js";
import type { AuthenticateWithPasskeyRequest } from "./authv1.js";
import type { AuthenticateWithPasskeyBeginResponse } from "./authv1.js";
import type { AuthenticateWithPasskeyBeginRequest } from "./authv1.js";
import type { GetAvailableAuthenticatorResponse } from "./authv1.js";
import type { GetAvailableAuthenticatorRequest } from "./authv1.js";
import type { AuthenticateAuthenticatorBeginResponse } from "./authv1.js";
import type { AuthenticateAuthenticatorBeginRequest } from "./authv1.js";
import type { RegisterAuthenticatorFinishResponse } from "./authv1.js";
import type { RegisterAuthenticatorFinishRequest } from "./authv1.js";
import type { RegisterAuthenticatorBeginResponse } from "./authv1.js";
import type { RegisterAuthenticatorBeginRequest } from "./authv1.js";
import type { OperationResult } from "../metav1/metav1.js";
import type { DeleteOptions } from "../metav1/metav1.js";
import type { AuthenticatorList } from "./authv1.js";
import type { ListAuthenticatorOptions } from "./authv1.js";
import type { CreateAuthenticatorRequest } from "./authv1.js";
import type { Authenticator } from "./authv1.js";
import type { GetOptions } from "../metav1/metav1.js";
import type { RegisterDeviceFinishResponse } from "./authv1.js";
import type { RegisterDeviceFinishRequest } from "./authv1.js";
import type { RegisterDeviceBeginResponse } from "./authv1.js";
import type { RegisterDeviceBeginRequest } from "./authv1.js";
import type { LogoutResponse } from "./authv1.js";
import type { LogoutRequest } from "./authv1.js";
import type { AuthenticateWithAuthenticatorRequest } from "./authv1.js";
import type { AuthenticateWithRefreshTokenRequest } from "./authv1.js";
import type { AuthenticateWithAssertionRequest } from "./authv1.js";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SessionToken } from "./authv1.js";
import type { AuthenticateWithAuthenticationTokenRequest } from "./authv1.js";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service octelium.api.main.auth.v1.MainService
 */
export interface IMainServiceClient {
    /**
     * @generated from protobuf rpc: AuthenticateWithAuthenticationToken
     */
    authenticateWithAuthenticationToken(input: AuthenticateWithAuthenticationTokenRequest, options?: RpcOptions): UnaryCall<AuthenticateWithAuthenticationTokenRequest, SessionToken>;
    /**
     * @generated from protobuf rpc: AuthenticateWithAssertion
     */
    authenticateWithAssertion(input: AuthenticateWithAssertionRequest, options?: RpcOptions): UnaryCall<AuthenticateWithAssertionRequest, SessionToken>;
    /**
     * @generated from protobuf rpc: AuthenticateWithRefreshToken
     */
    authenticateWithRefreshToken(input: AuthenticateWithRefreshTokenRequest, options?: RpcOptions): UnaryCall<AuthenticateWithRefreshTokenRequest, SessionToken>;
    /**
     * @generated from protobuf rpc: AuthenticateWithAuthenticator
     */
    authenticateWithAuthenticator(input: AuthenticateWithAuthenticatorRequest, options?: RpcOptions): UnaryCall<AuthenticateWithAuthenticatorRequest, SessionToken>;
    /**
     * @generated from protobuf rpc: Logout
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, LogoutResponse>;
    /**
     * @generated from protobuf rpc: RegisterDeviceBegin
     */
    registerDeviceBegin(input: RegisterDeviceBeginRequest, options?: RpcOptions): UnaryCall<RegisterDeviceBeginRequest, RegisterDeviceBeginResponse>;
    /**
     * @generated from protobuf rpc: RegisterDeviceFinish
     */
    registerDeviceFinish(input: RegisterDeviceFinishRequest, options?: RpcOptions): UnaryCall<RegisterDeviceFinishRequest, RegisterDeviceFinishResponse>;
    /**
     * @generated from protobuf rpc: GetAuthenticator
     */
    getAuthenticator(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Authenticator>;
    /**
     * @generated from protobuf rpc: CreateAuthenticator
     */
    createAuthenticator(input: CreateAuthenticatorRequest, options?: RpcOptions): UnaryCall<CreateAuthenticatorRequest, Authenticator>;
    /**
     * @generated from protobuf rpc: UpdateAuthenticator
     */
    updateAuthenticator(input: Authenticator, options?: RpcOptions): UnaryCall<Authenticator, Authenticator>;
    /**
     * @generated from protobuf rpc: ListAuthenticator
     */
    listAuthenticator(input: ListAuthenticatorOptions, options?: RpcOptions): UnaryCall<ListAuthenticatorOptions, AuthenticatorList>;
    /**
     * @generated from protobuf rpc: DeleteAuthenticator
     */
    deleteAuthenticator(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * @generated from protobuf rpc: RegisterAuthenticatorBegin
     */
    registerAuthenticatorBegin(input: RegisterAuthenticatorBeginRequest, options?: RpcOptions): UnaryCall<RegisterAuthenticatorBeginRequest, RegisterAuthenticatorBeginResponse>;
    /**
     * @generated from protobuf rpc: RegisterAuthenticatorFinish
     */
    registerAuthenticatorFinish(input: RegisterAuthenticatorFinishRequest, options?: RpcOptions): UnaryCall<RegisterAuthenticatorFinishRequest, RegisterAuthenticatorFinishResponse>;
    /**
     * @generated from protobuf rpc: AuthenticateAuthenticatorBegin
     */
    authenticateAuthenticatorBegin(input: AuthenticateAuthenticatorBeginRequest, options?: RpcOptions): UnaryCall<AuthenticateAuthenticatorBeginRequest, AuthenticateAuthenticatorBeginResponse>;
    /**
     * @generated from protobuf rpc: GetAvailableAuthenticator
     */
    getAvailableAuthenticator(input: GetAvailableAuthenticatorRequest, options?: RpcOptions): UnaryCall<GetAvailableAuthenticatorRequest, GetAvailableAuthenticatorResponse>;
    /**
     * @generated from protobuf rpc: AuthenticateWithPasskeyBegin
     */
    authenticateWithPasskeyBegin(input: AuthenticateWithPasskeyBeginRequest, options?: RpcOptions): UnaryCall<AuthenticateWithPasskeyBeginRequest, AuthenticateWithPasskeyBeginResponse>;
    /**
     * @generated from protobuf rpc: AuthenticateWithPasskey
     */
    authenticateWithPasskey(input: AuthenticateWithPasskeyRequest, options?: RpcOptions): UnaryCall<AuthenticateWithPasskeyRequest, SessionToken>;
}
/**
 * @generated from protobuf service octelium.api.main.auth.v1.MainService
 */
export class MainServiceClient implements IMainServiceClient, ServiceInfo {
    typeName = MainService.typeName;
    methods = MainService.methods;
    options = MainService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: AuthenticateWithAuthenticationToken
     */
    authenticateWithAuthenticationToken(input: AuthenticateWithAuthenticationTokenRequest, options?: RpcOptions): UnaryCall<AuthenticateWithAuthenticationTokenRequest, SessionToken> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthenticateWithAuthenticationTokenRequest, SessionToken>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AuthenticateWithAssertion
     */
    authenticateWithAssertion(input: AuthenticateWithAssertionRequest, options?: RpcOptions): UnaryCall<AuthenticateWithAssertionRequest, SessionToken> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthenticateWithAssertionRequest, SessionToken>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AuthenticateWithRefreshToken
     */
    authenticateWithRefreshToken(input: AuthenticateWithRefreshTokenRequest, options?: RpcOptions): UnaryCall<AuthenticateWithRefreshTokenRequest, SessionToken> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthenticateWithRefreshTokenRequest, SessionToken>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AuthenticateWithAuthenticator
     */
    authenticateWithAuthenticator(input: AuthenticateWithAuthenticatorRequest, options?: RpcOptions): UnaryCall<AuthenticateWithAuthenticatorRequest, SessionToken> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthenticateWithAuthenticatorRequest, SessionToken>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Logout
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, LogoutResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutRequest, LogoutResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RegisterDeviceBegin
     */
    registerDeviceBegin(input: RegisterDeviceBeginRequest, options?: RpcOptions): UnaryCall<RegisterDeviceBeginRequest, RegisterDeviceBeginResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterDeviceBeginRequest, RegisterDeviceBeginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RegisterDeviceFinish
     */
    registerDeviceFinish(input: RegisterDeviceFinishRequest, options?: RpcOptions): UnaryCall<RegisterDeviceFinishRequest, RegisterDeviceFinishResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterDeviceFinishRequest, RegisterDeviceFinishResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAuthenticator
     */
    getAuthenticator(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Authenticator> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Authenticator>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateAuthenticator
     */
    createAuthenticator(input: CreateAuthenticatorRequest, options?: RpcOptions): UnaryCall<CreateAuthenticatorRequest, Authenticator> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateAuthenticatorRequest, Authenticator>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateAuthenticator
     */
    updateAuthenticator(input: Authenticator, options?: RpcOptions): UnaryCall<Authenticator, Authenticator> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<Authenticator, Authenticator>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAuthenticator
     */
    listAuthenticator(input: ListAuthenticatorOptions, options?: RpcOptions): UnaryCall<ListAuthenticatorOptions, AuthenticatorList> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAuthenticatorOptions, AuthenticatorList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteAuthenticator
     */
    deleteAuthenticator(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RegisterAuthenticatorBegin
     */
    registerAuthenticatorBegin(input: RegisterAuthenticatorBeginRequest, options?: RpcOptions): UnaryCall<RegisterAuthenticatorBeginRequest, RegisterAuthenticatorBeginResponse> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterAuthenticatorBeginRequest, RegisterAuthenticatorBeginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RegisterAuthenticatorFinish
     */
    registerAuthenticatorFinish(input: RegisterAuthenticatorFinishRequest, options?: RpcOptions): UnaryCall<RegisterAuthenticatorFinishRequest, RegisterAuthenticatorFinishResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterAuthenticatorFinishRequest, RegisterAuthenticatorFinishResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AuthenticateAuthenticatorBegin
     */
    authenticateAuthenticatorBegin(input: AuthenticateAuthenticatorBeginRequest, options?: RpcOptions): UnaryCall<AuthenticateAuthenticatorBeginRequest, AuthenticateAuthenticatorBeginResponse> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthenticateAuthenticatorBeginRequest, AuthenticateAuthenticatorBeginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAvailableAuthenticator
     */
    getAvailableAuthenticator(input: GetAvailableAuthenticatorRequest, options?: RpcOptions): UnaryCall<GetAvailableAuthenticatorRequest, GetAvailableAuthenticatorResponse> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAvailableAuthenticatorRequest, GetAvailableAuthenticatorResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AuthenticateWithPasskeyBegin
     */
    authenticateWithPasskeyBegin(input: AuthenticateWithPasskeyBeginRequest, options?: RpcOptions): UnaryCall<AuthenticateWithPasskeyBeginRequest, AuthenticateWithPasskeyBeginResponse> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthenticateWithPasskeyBeginRequest, AuthenticateWithPasskeyBeginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AuthenticateWithPasskey
     */
    authenticateWithPasskey(input: AuthenticateWithPasskeyRequest, options?: RpcOptions): UnaryCall<AuthenticateWithPasskeyRequest, SessionToken> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthenticateWithPasskeyRequest, SessionToken>("unary", this._transport, method, opt, input);
    }
}
