name: Publish @octelium/apis

on:
  push:
    tags:
      - "apis/v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: packages/apis
        run: npm install

      - name: Build
        working-directory: packages/apis
        run: npx tsc

      - name: Publish stable
        if: "!contains(github.ref_name, '-pre.')"
        working-directory: packages/apis
        run: npm publish --access public --provenance

      - name: Publish pre-release
        if: contains(github.ref_name, '-pre.')
        working-directory: packages/apis
        run: npm publish --access public --tag next --provenance